export const vegetables = [
  { name: "Arvi", imgSrc: "/vegetables/arvi.jpg", price: 100 },
  { name: "Baby Onion", imgSrc: "/vegetables/babyonion.jpg", price: 120 },
  { name: "Baby Potato", imgSrc: "/vegetables/babypotato.jpg", price: 80 },
  { name: "Baby Spinach", imgSrc: "/vegetables/babyspinach.jpg", price: 150 },
  { name: "Beetroot", imgSrc: "/vegetables/beetroot.jpg", price: 90 },
  { name: "Brinjal Long", imgSrc: "/vegetables/brinjallong.jpg", price: 70 },
  { name: "Brinjal Round", imgSrc: "/vegetables/brinjalround.jpg", price: 75 },
  { name: "Broccoli", imgSrc: "/vegetables/broccoli.jpg", price: 130 },
  { name: "Cabbage", imgSrc: "/vegetables/cabbage.jpg", price: 60 },
  { name: "Capsicum", imgSrc: "/vegetables/capsicum.jpg", price: 110 },
  { name: "Cauliflower", imgSrc: "/vegetables/cauliflower.jpg", price: 120 },
  { name: "Celery", imgSrc: "/vegetables/celerylocal.jpg", price: 140 },
  { name: "Chili Green", imgSrc: "/vegetables/chilimalir.jpg", price: 90 },
  { name: "Chili Mirch", imgSrc: "/vegetables/chilimoro.jpg", price: 85 },
  {
    name: "Clean Green Kale",
    imgSrc: "/vegetables/cleangreenkale.jpg",
    price: 150,
  },
  { name: "Coriander", imgSrc: "/vegetables/coriander-dhania.jpg", price: 60 },
  { name: "Cucumber", imgSrc: "/vegetables/cucumber.jpg", price: 55 },
  { name: "Curry Leaves", imgSrc: "/vegetables/curryleaves.jpg", price: 50 },
  { name: "French Beans", imgSrc: "/vegetables/frenchbeans.jpg", price: 110 },
  { name: "Garlic China", imgSrc: "/vegetables/garlicchina.jpg", price: 180 },
  { name: "Garlic Desi", imgSrc: "/vegetables/garlicdesi.jpg", price: 160 },
  { name: "Ginger", imgSrc: "/vegetables/gingerdesi.jpg", price: 90 },
  {
    name: "Iceberg Lettuce",
    imgSrc: "/vegetables/iceberglettuce.jpg",
    price: 200,
  },
  { name: "Karela", imgSrc: "/vegetables/karela.jpg", price: 120 },
  { name: "Lemon", imgSrc: "/vegetables/lemon.jpg", price: 60 },
  { name: "Loki", imgSrc: "/vegetables/loki.jpg", price: 80 },
  { name: "New Potato", imgSrc: "/vegetables/newpotato.jpg", price: 70 },
  { name: "Onion", imgSrc: "/vegetables/onion.jpg", price: 65 },
  { name: "Parsley", imgSrc: "/vegetables/parsley.jpg", price: 100 },
  { name: "Peas", imgSrc: "/vegetables/peas.jpg", price: 130 },
  { name: "Pudina", imgSrc: "/vegetables/pudina.jpg", price: 50 },
  {
    name: "Purple Cabbage",
    imgSrc: "/vegetables/purplecabbage.jpg",
    price: 140,
  },
];
